all:
  children:
    bastion_hosts:
      hosts:
        bastion:
          ansible_host: 52.176.217.99
          ansible_user: azureuser
    
    app_servers:
      hosts:
        bastion:
          ansible_host: 52.176.217.99
          ansible_user: azureuser

  vars:
    ansible_python_interpreter: /usr/bin/python3