all:
  children:
    bastion_hosts:
      hosts:
        bastion:
          ansible_host: 52.176.217.99
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    app_servers:
      hosts:
        app-server:
          ansible_host: 74.249.251.94
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q azureuser@52.176.217.99" -o StrictHostKeyChecking=no'

  vars:
    ansible_python_interpreter: /usr/bin/python3