all:
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: 52.176.217.99
          ansible_user: azureuser
          ansible_ssh_private_key_file: ../terraform/e-library-key.pem
    
    app_servers:
      hosts:
        app-server:
          ansible_host: 74.249.251.94
          ansible_user: azureuser
          ansible_ssh_private_key_file: ../terraform/e-library-key.pem
          
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'